// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj6SO0H7j7ul1e8kUG5Lv-j8FanBEO4M8',
    appId: '1:447763793332:web:ed7f46e0a40d53def21ee1',
    messagingSenderId: '447763793332',
    projectId: 'qaro-cc38c',
    authDomain: 'qaro-cc38c.firebaseapp.com',
    storageBucket: 'qaro-cc38c.appspot.com',
    measurementId: 'G-QE5NNHX0GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIwLS1hcT1Lu7BS2qb0O6a3VCM-sGX5uc',
    appId: '1:447763793332:android:237a7604bccde241f21ee1',
    messagingSenderId: '447763793332',
    projectId: 'qaro-cc38c',
    storageBucket: 'qaro-cc38c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg8OlsMR-zh_IXXvi5gmdSCKMzdcdxaLs',
    appId: '1:447763793332:ios:203e9796fc9d2b5ef21ee1',
    messagingSenderId: '447763793332',
    projectId: 'qaro-cc38c',
    storageBucket: 'qaro-cc38c.appspot.com',
    iosClientId: '447763793332-tav7vugv9srvi2dha865tu5491lkjk4g.apps.googleusercontent.com',
    iosBundleId: 'com.besheger.qaroo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg8OlsMR-zh_IXXvi5gmdSCKMzdcdxaLs',
    appId: '1:447763793332:ios:203e9796fc9d2b5ef21ee1',
    messagingSenderId: '447763793332',
    projectId: 'qaro-cc38c',
    storageBucket: 'qaro-cc38c.appspot.com',
    iosClientId: '447763793332-tav7vugv9srvi2dha865tu5491lkjk4g.apps.googleusercontent.com',
    iosBundleId: 'com.besheger.qaroo',
  );
}
